[project]
name = "emby"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ai-edge-litert>=1.2.0",
    "onnx>=1.17.0",
    "onnxruntime>=1.21.0",
    "onnxslim>=0.1.50",
    "ultralytics>=8.3.108",
]
